name: Daily Social Media Monitor

on:
  schedule:
    - cron: '0 8 * * *'   # Run at 08:00 UTC
    - cron: '0 20 * * *'  # Run at 20:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run social media monitor
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: python main.py
      
    - name: Commit and push cache updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add cache.json
        git diff --staged --quiet || git commit -m "github action: update cache.json with latest post ids"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}